joint_impedance_controller:
  type: flexiv_controllers/JointImpedanceController
  joint_names:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
  k_p:
    - 3000.0
    - 3000.0
    - 800.0
    - 800.0
    - 200.0
    - 200.0
    - 200.0
  k_d:
    - 80.0
    - 80.0
    - 40.0
    - 40.0
    - 8.0
    - 8.0
    - 8.0
