# Settings for ros_control control loop
hardware_control_loop:
  loop_hz: &loop_hz 1000

# Settings for ros_control hardware interface
flexiv_hardware_interface:
  joints: &robot_joints
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: *loop_hz

position_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints: *robot_joints
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.01
    joint1: { goal: 0.05}
    joint2: { goal: 0.05}
    joint3: { goal: 0.05}
    joint4: { goal: 0.05}
    joint5: { goal: 0.05}
    joint6: { goal: 0.05}
    joint7: { goal: 0.05}
  stop_trajectory_duration: 0.5
  state_publish_rate: 100.0
  action_monitor_rate: 20.0

joint_impedance_controller:
  type: flexiv_controllers/JointImpedanceController
  joints: *robot_joints
  k_p:
    - 3000.0
    - 3000.0
    - 800.0
    - 800.0
    - 200.0
    - 200.0
    - 200.0
  k_d:
    - 80.0
    - 80.0
    - 40.0
    - 40.0
    - 8.0
    - 8.0
    - 8.0
